### PR TITLE
Downgrade font-awesome dependency to 5.x

### PR DESCRIPTION
**Pull request by gilles-gosuin**
escape-velocity template is not compatible with 6.x

### CODE REVIEW

**Comment by jamesward** [comment]
Just to verify, you want this released as `1.0.1` ?

**Comment by gilles-gosuin** [comment]
Yes, this is basically a bugfix. Thanks!

**Comment by jamesward** [comment]
Oh so making this `1.0.1` requires an upstream same version. But that release doesn't exist.  I can instead make this `1.0.0-1` if that is ok.

**Comment by gilles-gosuin** [comment]
You mean a release of https://github.com/gilles-gosuin/escape-velocity ?

As you noticed, this is unchanged, as the bug the requested release is intending to fix is actually in the WebJar's POM itself. Not sure how WebJars are to be versioned in that case.

**Comment by jamesward** [comment]
Cool. I'm releasing `1.0.0-1` now.

**Pull request merged**
